[project]
name = "sample-pw"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "pytest>=7.0",
  "playwright>=1.40",
  "pytest-playwright>=0.4.0",
  "pytest-order>=1.0.0",
  "pytest-html>=3.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"